# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pepperz's Place
email: me@smallpepperz.com
description: > # this means to ignore newlines until "baseurl:"
  Where I, SmallPepperZ, will be putting my various things™.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://smallpepperz.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
# twitter_username: SBootstrap
github_username:  SmallPepperZ
# facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

collections:
  error_pages:
    output: true

footer:
  about: 
    enabled: false
    text: "Stuff"
    label: "About Pepperz's Place"
  social_profiles: 
    enabled: true
    label: "Around the web"

# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       buttons:
#         -
#           enabled: true
#           text: Visit
#           icon: fa-link
#           url: /
#           color: 
#             bg: "#23272A"
#             fg: white
# Build settings
markdown: kramdown

destination: ../../www/main