#-------------------------------
# General Site Settings

title: SmallPepperZ
logo: 
author: smallpepperz
description: SmallPepperZ's Website
email: me@smallpepperz.com
discord: smallpepperz#0681
footer_msg: "<p onclick=window.open(\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\")>Don't Click</p>"

menu:
# - {name: About, link: '/about'}
# - {name: Blog, link: '/blog'}
- {name: Projects, link: '/projects'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m SmallPepperZ<br>Professional Human

# social:
# - {icon: "ti-facebook", link: "#"}
# - {icon: "ti-instagram", link: "#"}
# - {icon: "ti-dribbble", link: "#"}
# - {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Very good at spending hours on a 5 minute issue.

blurb-btn-link: '/about'
blurb-btn-name: See more


# About Page

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Python, color: '#306998', value: '60%'}
- {name: Borking Git Repositories, color: '#f1502f', value: '80%'}
- {name: Using Discord, color: '#738adb', value: '90%'}
- {name: Github, color: '#1B1B1B', value: '70%'}


#-------------------------------
# Portfolio (Section and Page)



# Portfolio Page
portfolio-label:
- {
    title : "Python",
    type : "python"
  }
- {
    title : "Java",
    type : "java"
  }
- {
    title : "Web Dev",
    type : "webdev"
  }


#-------------------------------
# Contact Section

contact-title: Contact Info
formspree-id: xnqwaerq